name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install library dependencies
        run: npm ci

      - name: Run library build
        run: npm run build

      - name: Install example dependencies
        run: cd example && npm ci

      - name: Run example build
        run: cd example && npm run build

      - name: Run example tests
        run: cd example && npm run test
